"""empty message

Revision ID: 7e28c6631079
Revises: 88c50371da7b
Create Date: 2019-08-22 02:24:39.023404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e28c6631079'
down_revision = '88c50371da7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
