"""empty message

Revision ID: 88c50371da7b
Revises: 4ea7cad7a133
Create Date: 2019-08-21 23:09:24.704566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88c50371da7b'
down_revision = '4ea7cad7a133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'products_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transactions', 'purchases_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'purchases_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('transactions', 'products_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
